# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_param.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setParameter(object):
    def setupUi(self, set_parameter):
        set_parameter.setObjectName("set_parameter")
        set_parameter.resize(329, 301)
        set_parameter.setWindowModality(QtCore.Qt.ApplicationModal)
        self.centralwidget = QtWidgets.QWidget(set_parameter)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.param1_txt = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.param1_txt.sizePolicy().hasHeightForWidth())
        self.param1_txt.setSizePolicy(sizePolicy)
        self.param1_txt.setObjectName("param1_txt")
        self.horizontalLayout.addWidget(self.param1_txt)
        self.fraction_volume_txt = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraction_volume_txt.sizePolicy().hasHeightForWidth())
        self.fraction_volume_txt.setSizePolicy(sizePolicy)
        self.fraction_volume_txt.setMinimumSize(QtCore.QSize(50, 0))
        self.fraction_volume_txt.setObjectName("fraction_volume_txt")
        self.horizontalLayout.addWidget(self.fraction_volume_txt)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.setall_param_btn = QtWidgets.QPushButton(self.centralwidget)
        self.setall_param_btn.setObjectName("setall_param_btn")
        self.horizontalLayout_3.addWidget(self.setall_param_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        set_parameter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(set_parameter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 329, 22))
        self.menubar.setObjectName("menubar")
        set_parameter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(set_parameter)
        self.statusbar.setObjectName("statusbar")
        set_parameter.setStatusBar(self.statusbar)

        self.retranslateUi(set_parameter)
        QtCore.QMetaObject.connectSlotsByName(set_parameter)

    def retranslateUi(self, set_parameter):
        _translate = QtCore.QCoreApplication.translate
        set_parameter.setWindowTitle(_translate("set_parameter", "Set Parameters"))
        self.param1_txt.setText(_translate("set_parameter", "Volume:"))
        self.fraction_volume_txt.setText(_translate("set_parameter", "5"))
        self.comboBox.setItemText(0, _translate("set_parameter", "ml"))
        self.comboBox.setItemText(1, _translate("set_parameter", "CV"))
        self.label_2.setText(_translate("set_parameter", "Flow Path:"))
        self.comboBox_2.setItemText(0, _translate("set_parameter", "Pre Column Waste"))
        self.comboBox_2.setItemText(1, _translate("set_parameter", "Post Column Waste"))
        self.comboBox_2.setItemText(2, _translate("set_parameter", "Fraction Column"))
        self.setall_param_btn.setText(_translate("set_parameter", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    set_parameter = QtWidgets.QMainWindow()
    ui = Ui_set_parameter()
    ui.setupUi(set_parameter)
    set_parameter.show()
    sys.exit(app.exec_())
