# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desgin_files/calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationWindow(object):
    def setupUi(self, CalibrationWindow):
        CalibrationWindow.setObjectName("CalibrationWindow")
        CalibrationWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        CalibrationWindow.resize(673, 496)
        self.centralwidget = QtWidgets.QWidget(CalibrationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setMinimumSize(QtCore.QSize(85, 85))
        self.stop_btn.setObjectName("stop_btn")
        self.horizontalLayout.addWidget(self.stop_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.column_size_lbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.column_size_lbl.setFont(font)
        self.column_size_lbl.setObjectName("column_size_lbl")
        self.gridLayout.addWidget(self.column_size_lbl, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.load_vol = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.load_vol.setFont(font)
        self.load_vol.setText("")
        self.load_vol.setObjectName("load_vol")
        self.gridLayout.addWidget(self.load_vol, 2, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        CalibrationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CalibrationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 673, 22))
        self.menubar.setObjectName("menubar")
        CalibrationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CalibrationWindow)
        self.statusbar.setObjectName("statusbar")
        CalibrationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CalibrationWindow)
        QtCore.QMetaObject.connectSlotsByName(CalibrationWindow)

    def retranslateUi(self, CalibrationWindow):
        _translate = QtCore.QCoreApplication.translate
        CalibrationWindow.setWindowTitle(_translate("CalibrationWindow", "Run Calibration Protocol"))
        self.stop_btn.setText(_translate("CalibrationWindow", "STOP"))
        self.start_btn.setText(_translate("CalibrationWindow", "START"))
        self.column_size_lbl.setText(_translate("CalibrationWindow", "1 mL"))
        self.label_3.setText(_translate("CalibrationWindow", "Column Size:"))
        self.label_2.setText(_translate("CalibrationWindow", "<html><head/><body><p>The calibration protocol will begin when start is clicked. </p><p>To change the column size close this window and change the column size in the main window<br/><br/><span style=\" font-weight:600;\">Protocol Description:</span></p><p>1 mL: The load is pumped for <span style=\" font-weight:600;\">10 minutes</span> into the first flow through column. The expected volume is <span style=\" font-weight:600;\">10mL</span>.</p><p>5mL: The load is pumped for <span style=\" font-weight:600;\">5 minutes</span> into the first flow through column. The expected volume is <span style=\" font-weight:600;\">25mL</span>.</p><p><span style=\" font-weight:600;\">Calibration Factor:</span></p><p>The calibration factor for each pump is the <span style=\" font-weight:600;\">Expected Volume/Actual Volume</span></p></body></html>"))
        self.label.setText(_translate("CalibrationWindow", "Run Calibration Protocol"))
        self.label_4.setText(_translate("CalibrationWindow", "Load Volume Needed: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalibrationWindow = QtWidgets.QMainWindow()
    ui = Ui_CalibrationWindow()
    ui.setupUi(CalibrationWindow)
    CalibrationWindow.show()
    sys.exit(app.exec_())
