#!/usr/bin/env python
from czpurifier.ui import UICommands

# Setup
ui = UICommands()
ui.connect('1mL', 'pure1')
ui.resetMachine()

# Purge bubbles
ui.openLoad()
ui.pump(1)
ui.closeLoad()
ui.selectPort('BLEACH')
ui.pump(1)
ui.selectPort('ELUTION')
ui.pump(1)
ui.selectPort('WASH')
ui.pump(1)
ui.selectPort('LOAD_BUFFER')
ui.pump(1)
ui.closePreColumnWaste()

# Run purification protocol
ui.pump(20)
ui.openLoad()
ui.pump(50)
ui.closeLoad()
ui.pump(10)
ui.selectPort('ELUTION')
ui.openPreColumnWaste()
ui.pump(1)
ui.closeAllWaste()
ui.selectFraction('Frac1')
ui.pump(1)
ui.selectFraction('Frac2')
ui.pump(1)
ui.selectFraction('Frac3')
ui.pump(1)
ui.selectFraction('Frac4')
ui.pump(1)
ui.selectFraction('Frac5')
ui.pump(1)
ui.selectFraction('Frac6')
ui.pump(1)
ui.selectFraction('Frac7')
ui.pump(1)
ui.selectFraction('Frac8')
ui.pump(1)
ui.selectFraction('Frac9')
ui.pump(1)
ui.selectFraction('Frac10')
ui.pump(1)
ui.selectFraction('Flow1')
ui.pump(10)
ui.selectFraction('Flow2')
ui.pump(10)
ui.selectFraction('Flow3')
ui.pump(10)
ui.selectFraction('Flow4')
ui.pump(10)
ui.openPostColumnWaste()
ui.selectFraction('Safe')

# Run cleanup
ui.selectPort('BLEACH')
ui.pump(10)
